FROM node:12.13.1 as build-frontend

WORKDIR /app
COPY frontend/package*.json .
RUN yarn install
COPY frontend/ .
RUN yarn build



FROM nginx

# override default conf of nginx
COPY nginx/nginx.prod.conf /etc/nginx/conf.d/default.conf

# copy static files
COPY --from=build-frontend /app/build/ /var/www/html

