FROM node:12.13.1 as build-frontend

WORKDIR /app
COPY frontend/package*.json .
RUN yarn install
COPY frontend/ .
RUN yarn build



FROM nginx

WORKDIR /
# override default conf of nginx
COPY nginx/nginx.prod.conf /nginx.conf
COPY nginx/entrypoint.sh entrypoint.sh

# copy static files
COPY --from=build-frontend /app/build/ /var/www/html

# if we directly use entrypoint.sh
# we need to set the permission using RUN command
# which will create extra image layer
ENTRYPOINT ["sh", "/entrypoint.sh"]
