# Generated by Django 3.0.1 on 2019-12-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezoneuser',
            name='is_user_manager',
            field=models.BooleanField(default=False),
        ),
    ]
