# Generated by Django 3.0.1 on 2019-12-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_timezoneuser_is_user_manager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='timezoneuser',
            managers=[
            ],
        ),
    ]
