# Generated by Django 3.0.1 on 2019-12-28 05:42

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191228_0541'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='timezoneuser',
            managers=[
                ('objects', accounts.models.TimeZoneUserManager()),
            ],
        ),
    ]
