# Generated by Django 3.0.1 on 2019-12-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191228_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezoneuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
